import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, FileText, Save, Download, CheckCircle, Info } from 'lucide-react';
import { apiFetch, auth } from '../utils/api';
import Layout from '../components/Layout';

const AgreementEditor = () => {
    const { targetId } = useParams();
    const navigate = useNavigate();
    const userId = auth.getUserId();
    
    const [content, setContent] = useState('');
    const [status, setStatus] = useState('');
    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);
    const [msg, setMsg] = useState('');

    useEffect(() => {
        const load = async () => {
            try {
                const data = await apiFetch(`/agreement/${userId}/${targetId}`);
                setContent(data?.content || '');
                setStatus(data?.status || 'template');
            } catch (err) {
                console.error('Failed to load agreement');
            } finally {
                setLoading(false);
            }
        };
        load();
    }, [userId, targetId]);

    const handleSave = async () => {
        setSaving(true);
        setMsg('');
        try {
            await apiFetch('/agreement', {
                method: 'POST',
                body: { userA_id: userId, userB_id: targetId, content }
            });
            setMsg('Agreement saved successfully!');
            setStatus('draft');
        } catch (err) {
            setMsg('Error saving agreement');
        } finally {
            setSaving(false);
        }
    };

    const downloadTxt = () => {
        const element = document.createElement("a");
        const file = new Blob([content], {type: 'text/plain'});
        element.href = URL.createObjectURL(file);
        element.download = "Roommate_Agreement.txt";
        document.body.appendChild(element);
        element.click();
    };

    if (loading) return <Layout><div className="p-20 text-center">Loading contract draft...</div></Layout>;

    return (
        <Layout activePage="shortlist">
            <div className="max-w-4xl mx-auto px-4 pt-6 pb-20">
                {/* Header */}
                <div className="flex items-center justify-between mb-8">
                    <div className="flex items-center gap-3">
                        <button onClick={() => navigate(-1)} className="btn-ghost p-2">
                            <ArrowLeft size={20} />
                        </button>
                        <div>
                            <h1 className="font-display font-bold text-xl">Roommate Agreement</h1>
                            <p className="text-[10px] text-text-muted uppercase font-bold tracking-widest">Co-living Governance</p>
                        </div>
                    </div>
                    
                    <div className="flex gap-2">
                        <button onClick={downloadTxt} className="btn-secondary px-4 py-2 text-xs">
                             <Download size={14} /> Download
                        </button>
                        <button 
                            onClick={handleSave} 
                            disabled={saving}
                            className="btn-primary px-5 py-2 text-xs"
                        >
                             {saving ? 'Saving...' : <><Save size={14} /> Save Draft</>}
                        </button>
                    </div>
                </div>

                {msg && (
                    <div className="mb-6 p-3 bg-green-50 border border-green-100 rounded-xl text-green-700 text-xs text-center font-bold flex items-center justify-center gap-2">
                        <CheckCircle size={14} /> {msg}
                    </div>
                )}

                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                    {/* Editor Main */}
                    <div className="lg:col-span-2">
                        <div className="card-soft p-1 space-y-1 bg-white shadow-soft ring-1 ring-surface-border">
                            <div className="bg-surface-muted/30 p-4 border-b border-surface-border">
                                <div className="flex items-center gap-2 text-xs font-bold text-text-muted">
                                    <FileText size={14} /> 
                                    {status === 'template' ? 'AUTOGENERATED TEMPLATE' : 'DRAFT AGREEMENT'}
                                </div>
                            </div>
                            <textarea
                                className="w-full min-h-[600px] p-8 text-sm font-mono leading-relaxed focus:outline-none border-none bg-transparent text-text-primary"
                                value={content}
                                onChange={(e) => setContent(e.target.value)}
                                placeholder="Write your roommate agreement here..."
                            />
                        </div>
                    </div>

                    {/* Sidebar Tips */}
                    <div className="space-y-4">
                        <div className="card p-6 bg-brand-secondary/10 border-brand-primary/20">
                            <h3 className="text-xs font-bold uppercase tracking-widest text-brand-deep mb-4 flex items-center gap-2">
                                <Info size={14} /> Negotiation Tips
                            </h3>
                            <ul className="space-y-3">
                                {[
                                    'Define clear guest boundaries',
                                    'Specific cleaning rota works best',
                                    'Agree on shared groceries',
                                    'Set noise-free work windows'
                                ].map((tip, i) => (
                                    <li key={i} className="text-xs text-text-secondary flex gap-2">
                                        <div className="w-1.5 h-1.5 rounded-full bg-brand-primary mt-1 flex-shrink-0" />
                                        {tip}
                                    </li>
                                ))}
                            </ul>
                        </div>

                        <div className="card p-6 bg-surface-muted/30 text-[10px] text-text-muted leading-relaxed">
                            <strong>Note:</strong> This document is a mutual understanding between roommates. While it helps resolve conflicts, consult local laws for formal lease requirements in your city.
                        </div>
                    </div>
                </div>
            </div>
        </Layout>
    );
};

export default AgreementEditor;
